esphome:
  name: esp-smoke
  friendly_name: esp-smoke
  libraries:
    - SPI
    - RF24
  includes:
    - Smoke_Receiver.h

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: #redacted#

ota:
  password: #redacted#
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  manual_ip:
    static_ip: #redacted#
    gateway: #redacted#
    subnet: #redacted#

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: #redacted#
    password: #redacted#

captive_portal:

sensor:
- platform: custom
  lambda: |-
    auto smoke = new Smoke_Receiver();
    App.register_component(smoke);
    return {smoke->probe1_temp, smoke->probe1_min, smoke->probe1_max, smoke->probe2_temp, smoke->probe2_min, smoke->probe2_max};

  sensors:
  - name: "Smoke Probe 1 Temperature"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Smoke Probe 1 Min Alarm"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Smoke Probe 1 Max Alarm"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Smoke Probe 2 Temperature"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Smoke Probe 2 Min Alarm"
    unit_of_measurement: °F
    accuracy_decimals: 1
  - name: "Smoke Probe 2 Max Alarm"
    unit_of_measurement: °F
    accuracy_decimals: 1